window.CRO_CHECKLIST = [
  {
    "id": "general-main-pages-home-page-landing-page-product-page-load-quickly-5-seconds-",
    "page": "general",
    "pageLabel": "General",
    "section": "General",
    "checkpoint": "Main pages (home page, landing page, product page) load quickly (5 seconds or less)",
    "impact": 3.0,
    "cost": 3.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "general-every-page-has-a-cta-even-404-error-pages-result-page-with-0-results-b",
    "page": "general",
    "pageLabel": "General",
    "section": "General",
    "checkpoint": "Every page has a CTA (even 404 error pages, result page with 0 results, blog posts, about us page)",
    "impact": 1.0,
    "cost": 1.0,
    "priorityScore": 4,
    "defaultEvaluation": "Can be Improved",
    "tier": "basic"
  },
  {
    "id": "general-things-that-are-clickable-like-buttons-are-obviously-pressable-hover-s",
    "page": "general",
    "pageLabel": "General",
    "section": "General",
    "checkpoint": "Things that are clickable (like buttons) are obviously pressable (hover states, rounded corners, subtle gradient, blue underlined links)",
    "impact": 2.0,
    "cost": 1.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "general-cookie-notification-bar-can-be-easily-closed-or-approved-under-2-secon",
    "page": "general",
    "pageLabel": "General",
    "section": "General",
    "checkpoint": "Cookie notification bar can be easily closed or approved (under 2 seconds)",
    "impact": 1.0,
    "cost": 1.0,
    "priorityScore": 5.4,
    "defaultEvaluation": "Bad",
    "tier": "basic"
  },
  {
    "id": "general-the-site-offers-wishlists-which-is-the-easiest-first-step-in-the-check",
    "page": "general",
    "pageLabel": "General",
    "section": "General",
    "checkpoint": "The site offers wishlists which is the easiest first step in the checkout process",
    "impact": 2.0,
    "cost": 3.0,
    "priorityScore": 4,
    "defaultEvaluation": "Bad",
    "tier": "basic"
  },
  {
    "id": "general-button-labels-and-link-labels-start-with-a-verb-and-time-e-g-shop-now",
    "page": "general",
    "pageLabel": "General",
    "section": "General",
    "checkpoint": "Button labels and link labels start with a verb and time (e.g. \"Shop Now\") ",
    "impact": 2.0,
    "cost": 1.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "general-items-that-aren-t-clickable-do-not-have-characteristics-that-suggest-t",
    "page": "general",
    "pageLabel": "General",
    "section": "General",
    "checkpoint": "Items that aren't clickable do not have characteristics that suggest that they are",
    "impact": 2.0,
    "cost": 1.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "general-there-is-sufficient-space-between-action-targets-buttons-forms-to-prev",
    "page": "general",
    "pageLabel": "General",
    "section": "General",
    "checkpoint": "There is sufficient space between action targets (buttons, forms) to prevent the user from hitting multiple or incorrect targets",
    "impact": 1.0,
    "cost": 1.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "general-the-store-offers-upsell-opportunities-between-the-checkout-page-and-th",
    "page": "general",
    "pageLabel": "General",
    "section": "General",
    "checkpoint": "The store offers upsell opportunities between the checkout page and thank you page; if the user decides to add another product to the order, he doesn't need to input all the payment info again",
    "impact": 3.0,
    "cost": 3.0,
    "priorityScore": 5.4,
    "defaultEvaluation": "Bad",
    "tier": "basic"
  },
  {
    "id": "general-the-shop-s-logo-is-placed-in-the-same-location-on-every-page-clicking-",
    "page": "general",
    "pageLabel": "General",
    "section": "General",
    "checkpoint": "The shop's logo is placed in the same location on every page; clicking the logo returns the user to the most logical page (e.g. home page)",
    "impact": 2.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "general-the-website-uses-subtle-micro-animations-e-g-pulses-to-emphasise-the-m",
    "page": "general",
    "pageLabel": "General",
    "section": "General",
    "checkpoint": "The website uses subtle micro-animations (e.g. pulses) to emphasise the main CTA on every page",
    "impact": 2.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "general-the-site-doesn-t-include-annoying-pop-ups-at-the-wrong-time-too-early-",
    "page": "general",
    "pageLabel": "General",
    "section": "General",
    "checkpoint": "The site doesn't include annoying pop-ups at the wrong time (too early in the process)",
    "impact": 2.0,
    "cost": 1.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "general-the-home-page-promotes-site-wide-offers-at-the-top-of-the-page-e-g-fre",
    "page": "general",
    "pageLabel": "General",
    "section": "General",
    "checkpoint": "The home page promotes site-wide offers at the top of the page (e.g. Free Shipping) with urgency and scarcity triggers (\"Only today\") and a linked CTA (\"Shop best-sellers now\")",
    "impact": 3.0,
    "cost": 1.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "general-the-top-bar-with-a-site-wide-offer-is-prominent-with-a-clear-cta",
    "page": "general",
    "pageLabel": "General",
    "section": "General",
    "checkpoint": "The top bar with a site-wide offer is prominent, with a clear CTA",
    "impact": 3.0,
    "cost": 1.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "general-the-navigation-system-is-broad-and-shallow-many-items-per-menu-level-r",
    "page": "general",
    "pageLabel": "General",
    "section": "Navigation",
    "checkpoint": "The navigation system is broad and shallow (many items per menu level) rather than deep (many menu levels)",
    "impact": 2.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "general-good-navigational-feedback-is-provided-e-g-showing-active-state-of-whe",
    "page": "general",
    "pageLabel": "General",
    "section": "Navigation",
    "checkpoint": "Good navigational feedback is provided (e.g. showing active state of where you are on the site)",
    "impact": 2.0,
    "cost": 1.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "general-category-labels-accurately-describe-the-information-in-the-category",
    "page": "general",
    "pageLabel": "General",
    "section": "Navigation",
    "checkpoint": "Category labels accurately describe the information in the category",
    "impact": 3.0,
    "cost": 1.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "general-navigation-items-are-ordered-in-the-most-logical-or-task-oriented-mann",
    "page": "general",
    "pageLabel": "General",
    "section": "Navigation",
    "checkpoint": "Navigation items are ordered in the most logical or task-oriented manner (with the less important corporate information at the bottom)",
    "impact": 3.0,
    "cost": 1.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "general-main-navigation-doesn-t-include-unnecessary-links-e-g-privacy-policy-r",
    "page": "general",
    "pageLabel": "General",
    "section": "Navigation",
    "checkpoint": "Main navigation doesn't include unnecessary links (e.g. privacy policy, return policy, and terms and conditions)",
    "impact": 2.0,
    "cost": 1.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "general-store-uses-sticky-navigation-so-the-categories-first-page-search-and-c",
    "page": "general",
    "pageLabel": "General",
    "section": "Navigation",
    "checkpoint": "Store uses sticky navigation, so the categories, first page, search and cart widget are easily accessible all the time",
    "impact": 2.0,
    "cost": 3.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "general-the-home-page-contains-a-prominent-search-box-near-the-top-or-top-righ",
    "page": "general",
    "pageLabel": "General",
    "section": "Search bar",
    "checkpoint": "The home page contains a prominent search box near the top (or top-right) of the website",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "general-the-search-bar-has-an-auto-complete-and-auto-suggest-option",
    "page": "general",
    "pageLabel": "General",
    "section": "Search bar",
    "checkpoint": "The search bar has an auto-complete and auto-suggest option",
    "impact": 3.0,
    "cost": 3.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "general-auto-suggest-searches-through-categories-and-products",
    "page": "general",
    "pageLabel": "General",
    "section": "Search bar",
    "checkpoint": "Auto-suggest searches through categories and products",
    "impact": 2.0,
    "cost": 3.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "general-the-search-results-page-shows-the-user-what-was-searched-for-it-is-eas",
    "page": "general",
    "pageLabel": "General",
    "section": "Search bar",
    "checkpoint": "The search results page shows the user what was searched for; it is easy to edit and resubmit the search",
    "impact": 2.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "general-search-results-are-clear-useful-and-ranked-by-relevance-and-how-many-r",
    "page": "general",
    "pageLabel": "General",
    "section": "Search bar",
    "checkpoint": "Search results are clear, useful, and ranked by relevance and how many results were retrieved",
    "impact": 2.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "general-if-no-results-are-returned-the-search-engine-gracefully-oh-snap-offers",
    "page": "general",
    "pageLabel": "General",
    "section": "Search bar",
    "checkpoint": "If no results are returned, the search engine gracefully (\"oh, snap\") offers ideas or options for improving the query based on identifiable problems with the user's input",
    "impact": 1.0,
    "cost": 2.0,
    "priorityScore": 3,
    "defaultEvaluation": "Can be Improved",
    "tier": "basic"
  },
  {
    "id": "general-the-most-common-queries-as-reflected-in-analytics-produce-useful-resul",
    "page": "general",
    "pageLabel": "General",
    "section": "Search bar",
    "checkpoint": "The most common queries (as reflected in analytics) produce useful results",
    "impact": 2.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "general-the-search-engine-includes-templates-examples-or-hints-on-how-it-can-b",
    "page": "general",
    "pageLabel": "General",
    "section": "Search bar",
    "checkpoint": "The search engine includes templates, examples or hints on how it can be used effectively: verb + item (e.g. search \"men's hat, blue leggings, XL pullovers\")",
    "impact": 2.0,
    "cost": 1.0,
    "priorityScore": 5,
    "defaultEvaluation": "Can be Improved",
    "tier": "basic"
  },
  {
    "id": "general-the-search-box-is-long-enough-to-handle-common-query-lengths",
    "page": "general",
    "pageLabel": "General",
    "section": "Search bar",
    "checkpoint": "The search box is long enough to handle common query lengths",
    "impact": 1.0,
    "cost": 1.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "general-the-search-box-gives-results-if-you-press-enter",
    "page": "general",
    "pageLabel": "General",
    "section": "Search bar",
    "checkpoint": "The search box gives results if you press Enter",
    "impact": 1.0,
    "cost": 1.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "general-the-search-box-contains-a-magnifying-glass-icon-that-clearly-represent",
    "page": "general",
    "pageLabel": "General",
    "section": "Search bar",
    "checkpoint": "The search box contains a \"magnifying glass\" icon that clearly represents the search function",
    "impact": 2.0,
    "cost": 1.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "general-once-you-click-on-the-search-field-and-before-you-type-in-anything-the",
    "page": "general",
    "pageLabel": "General",
    "section": "Search bar",
    "checkpoint": "Once you click on the search field and before you type in anything, the search gives you hints of your recent searches or trending searches",
    "impact": 2.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "general-the-search-engine-provides-automatic-spell-checking-and-searches-for-p",
    "page": "general",
    "pageLabel": "General",
    "section": "Search bar",
    "checkpoint": "The search engine provides automatic spell checking and searches for plurals and synonyms",
    "impact": 2.0,
    "cost": 3.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "general-cart-widget-is-easibly-accesible-on-every-page-in-the-top-right-corner",
    "page": "general",
    "pageLabel": "General",
    "section": "Cart widget in the header",
    "checkpoint": "Cart widget is easibly accesible on every page in the top-right corner",
    "impact": 3.0,
    "cost": 3.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "general-mini-cart-widget-includes-the-total-price-total-discount-number-of-ite",
    "page": "general",
    "pageLabel": "General",
    "section": "Cart widget in the header",
    "checkpoint": "Mini cart widget includes the total price, total discount, number of items, all items in the cart (on hover) and it's prominent on every page",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "general-if-the-store-has-a-free-shipping-option-the-cart-widget-clearly-states",
    "page": "general",
    "pageLabel": "General",
    "section": "Cart widget in the header",
    "checkpoint": "If the store has a free shipping option, the cart widget clearly states how far away the user is from getting free shipping",
    "impact": 3.0,
    "cost": 3.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "general-a-link-to-both-the-basket-and-checkout-is-clearly-visible-on-the-mini-",
    "page": "general",
    "pageLabel": "General",
    "section": "Cart widget in the header",
    "checkpoint": "A link to both the basket and checkout is clearly visible on the mini-cart widget",
    "impact": 3.0,
    "cost": 1.0,
    "priorityScore": 6,
    "defaultEvaluation": "Can be Improved",
    "tier": "basic"
  },
  {
    "id": "general-empty-cart-widget-has-on-hover-cta-to-shop-our-best-sellers",
    "page": "general",
    "pageLabel": "General",
    "section": "Cart widget in the header",
    "checkpoint": "Empty cart widget has (on hover) CTA to \"Shop our best-sellers\"",
    "impact": 1.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "general-footer-highlights-benefits-of-shopping-at-the-store-e-g-free-shipping-",
    "page": "general",
    "pageLabel": "General",
    "section": "Footer",
    "checkpoint": "Footer highlights benefits of shopping at the store (e.g. free shipping, returns, money back, 19k products shipped this month, contact information)",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 6.7,
    "defaultEvaluation": "Bad",
    "tier": "basic"
  },
  {
    "id": "general-footer-contains-a-back-to-top-link-so-the-user-can-easily-go-back-to-t",
    "page": "general",
    "pageLabel": "General",
    "section": "Footer",
    "checkpoint": "Footer contains a \"Back to top\" link so the user can easily go back to the top",
    "impact": 1.0,
    "cost": 1.0,
    "priorityScore": 5.4,
    "defaultEvaluation": "Bad",
    "tier": "basic"
  },
  {
    "id": "general-it-is-clear-that-there-is-a-real-organisation-behind-the-site-e-g-ther",
    "page": "general",
    "pageLabel": "General",
    "section": "Footer",
    "checkpoint": "It is clear that there is a real organisation behind the site (e.g. there is a physical address or a photo of the office)",
    "impact": 2.0,
    "cost": 1.0,
    "priorityScore": 5,
    "defaultEvaluation": "Can be Improved",
    "tier": "basic"
  },
  {
    "id": "general-it-is-easy-to-see-the-return-policy-privacy-policy-and-terms-condition",
    "page": "general",
    "pageLabel": "General",
    "section": "Footer",
    "checkpoint": "It is easy to see the return policy, privacy policy and terms & conditions on any given page with one click",
    "impact": 1.0,
    "cost": 1.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "general-footer-shows-trust-icons-seal-badges-e-g-verified-by-norton-along-with",
    "page": "general",
    "pageLabel": "General",
    "section": "Footer",
    "checkpoint": "Footer shows trust icons / seal badges (e.g. verified by Norton) along with reassuring copy (e.g. \"Shop with confidence\")",
    "impact": 2.0,
    "cost": 1.0,
    "priorityScore": 5,
    "defaultEvaluation": "Can be Improved",
    "tier": "basic"
  },
  {
    "id": "general-footer-includes-links-to-social-networks-and-a-total-number-of-likes-f",
    "page": "general",
    "pageLabel": "General",
    "section": "Footer",
    "checkpoint": "Footer includes links to social networks and a total number of likes/followers (so that the user can check them for trust)",
    "impact": 1.0,
    "cost": 1.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "general-footer-includes-links-to-main-categories",
    "page": "general",
    "pageLabel": "General",
    "section": "Footer",
    "checkpoint": "Footer includes links to main categories",
    "impact": 2.0,
    "cost": 1.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "home-the-home-page-promotes-site-wide-offers-on-top-of-the-page-e-g-free-sh",
    "page": "home",
    "pageLabel": "Home page",
    "section": "General",
    "checkpoint": "The home page promotes site-wide offers on top of the page (e.g. Free Shipping) with urgency and scarcity triggers",
    "impact": 3.0,
    "cost": 1.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "home-the-home-page-is-professionally-designed-not-overloaded-and-it-creates",
    "page": "home",
    "pageLabel": "Home page",
    "section": "General",
    "checkpoint": "The home page is professionally designed, not overloaded, and it creates a positive first impression ",
    "impact": 3.0,
    "cost": 3.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "home-once-you-land-on-the-homepage-you-know-the-main-products-that-the-stor",
    "page": "home",
    "pageLabel": "Home page",
    "section": "General",
    "checkpoint": "Once you land on the homepage, you know the main products that the store is selling",
    "impact": 3.0,
    "cost": 1.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "home-the-home-page-follows-a-clear-straightfowrard-visual-hierarchy",
    "page": "home",
    "pageLabel": "Home page",
    "section": "General",
    "checkpoint": "The home page follows a clear, straightfowrard visual hierarchy",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "home-the-value-proposition-is-clearly-stated-on-the-home-page-e-g-with-a-ta",
    "page": "home",
    "pageLabel": "Home page",
    "section": "General",
    "checkpoint": "The value proposition is clearly stated on the home page (e.g. with a tagline or welcome blurb)",
    "impact": 3.0,
    "cost": 1.0,
    "priorityScore": 8,
    "defaultEvaluation": "Bad",
    "tier": "basic"
  },
  {
    "id": "home-the-home-page-contains-meaningful-high-quality-graphics-not-clip-art-o",
    "page": "home",
    "pageLabel": "Home page",
    "section": "General",
    "checkpoint": "The home page contains meaningful high-quality graphics, not clip art or pictures of models",
    "impact": 2.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "home-the-home-page-contains-one-or-two-e-g-shop-for-men-shop-for-women-visu",
    "page": "home",
    "pageLabel": "Home page",
    "section": "General",
    "checkpoint": "The home page contains one or two (e.g. Shop for men, Shop for women) visually prominent CTAs above the fold and it has relevant copy (e.g. Start shopping)",
    "impact": 3.0,
    "cost": 1.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "home-the-home-page-highlights-any-specific-deals-special-offers-or-urgency-",
    "page": "home",
    "pageLabel": "Home page",
    "section": "General",
    "checkpoint": "The home page highlights any specific deals, special offers or urgency offers near the top",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 5,
    "defaultEvaluation": "Can be Improved",
    "tier": "basic"
  },
  {
    "id": "home-the-home-page-highlights-the-main-benefits-of-shopping-with-you-e-g-ve",
    "page": "home",
    "pageLabel": "Home page",
    "section": "General",
    "checkpoint": "The home page highlights the main benefits of shopping with you (e.g. \"Vegan friendly\", \"We give back to charity\", \"Not tested on animals\", \"19,222 products successfully shipped and delivered this month alone\")",
    "impact": 3.0,
    "cost": 1.0,
    "priorityScore": 8,
    "defaultEvaluation": "Bad",
    "tier": "basic"
  },
  {
    "id": "home-the-most-important-product-categories-are-shown-first-with-descriptive",
    "page": "home",
    "pageLabel": "Home page",
    "section": "General",
    "checkpoint": "The most important product categories are shown first, with descriptive photos near the top of the homepage",
    "impact": 2.0,
    "cost": 1.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "home-the-store-uses-special-category-pages-best-sellers-new-sale-30-off-etc",
    "page": "home",
    "pageLabel": "Home page",
    "section": "General",
    "checkpoint": "The store uses special category pages (best-sellers, new, sale, \"30% off\", etc.) that take users into a shopping mode",
    "impact": 2.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "home-there-is-a-short-list-of-the-most-important-products-supplemented-with",
    "page": "home",
    "pageLabel": "Home page",
    "section": "General",
    "checkpoint": "There is a short list of the most important products supplemented with links on the home page",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "home-the-home-page-contains-an-option-for-customers-to-contact-the-store-e-",
    "page": "home",
    "pageLabel": "Home page",
    "section": "General",
    "checkpoint": "The home page contains an option for customers to contact the store (e.g. live chat, email, or phone number)",
    "impact": 2.0,
    "cost": 1.0,
    "priorityScore": 5,
    "defaultEvaluation": "Can be Improved",
    "tier": "basic"
  },
  {
    "id": "home-the-home-page-shows-recently-viewed-items-for-returning-visitors",
    "page": "home",
    "pageLabel": "Home page",
    "section": "General",
    "checkpoint": "The home page shows recently viewed items for returning visitors",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 6.7,
    "defaultEvaluation": "Bad",
    "tier": "basic"
  },
  {
    "id": "home-the-story-of-the-founders-behind-the-product-and-store-is-shown-along-",
    "page": "home",
    "pageLabel": "Home page",
    "section": "General",
    "checkpoint": "The story of the founders behind the product and store is shown, along with their mission and vision",
    "impact": 2.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "home-the-home-page-contains-general-customer-reviews-or-product-specifics-w",
    "page": "home",
    "pageLabel": "Home page",
    "section": "Social proof",
    "checkpoint": "The home page contains general customer reviews or product specifics with a link to the product itself",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "home-the-home-page-shows-overall-store-ratings-from-authoritative-review-si",
    "page": "home",
    "pageLabel": "Home page",
    "section": "Social proof",
    "checkpoint": "The home page shows overall store ratings from authoritative review sites (e.g. Trustpilot, Reviews.com, Yotpo, Podium)",
    "impact": 3.0,
    "cost": 1.0,
    "priorityScore": 6,
    "defaultEvaluation": "Can be Improved",
    "tier": "basic"
  },
  {
    "id": "home-the-home-page-contains-awards-trust-badges-and-certificates-earned-by-",
    "page": "home",
    "pageLabel": "Home page",
    "section": "Social proof",
    "checkpoint": "The home page contains awards, trust-badges, and certificates earned by the store",
    "impact": 3.0,
    "cost": 1.0,
    "priorityScore": 6,
    "defaultEvaluation": "Can be Improved",
    "tier": "basic"
  },
  {
    "id": "home-the-home-page-highlights-logos-of-news-sites-blogs-celebrities-where-t",
    "page": "home",
    "pageLabel": "Home page",
    "section": "Social proof",
    "checkpoint": "The home page highlights logos of news sites/blogs/celebrities where the product/brand has had any PR exposure (e.g. \"Used by executives at Fortune 500\")",
    "impact": 3.0,
    "cost": 1.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "home-the-home-page-highlights-logos-of-well-known-brands",
    "page": "home",
    "pageLabel": "Home page",
    "section": "Social proof",
    "checkpoint": "The home page highlights logos of well-known brands",
    "impact": 2.0,
    "cost": 1.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "home-the-home-page-contains-user-generated-photos-e-g-from-instagram",
    "page": "home",
    "pageLabel": "Home page",
    "section": "Social proof",
    "checkpoint": "The home page contains user-generated photos (e.g. from Instagram)",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 5,
    "defaultEvaluation": "Can be Improved",
    "tier": "basic"
  },
  {
    "id": "category-users-can-sort-category-page-e-g-ordering-by-price-best-sellers-new-it",
    "page": "category",
    "pageLabel": "Category page",
    "section": "General",
    "checkpoint": "Users can sort category page (e.g. ordering by price, \"best-sellers\", \"new items\", \"most popular\", or \"most discounted\")",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "category-the-sorting-feature-is-shown-in-the-top-right-corner-above-the-product",
    "page": "category",
    "pageLabel": "Category page",
    "section": "General",
    "checkpoint": "The sorting feature is shown in the top-right corner above the product list/grid",
    "impact": 2.0,
    "cost": 1.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "category-category-page-has-clear-and-understandable-sub-category-names",
    "page": "category",
    "pageLabel": "Category page",
    "section": "General",
    "checkpoint": "Category page has clear and understandable (sub)category names",
    "impact": 2.0,
    "cost": 1.0,
    "priorityScore": 0,
    "defaultEvaluation": "Not Relevant",
    "tier": "basic"
  },
  {
    "id": "category-category-page-uses-relevant-category-page-design-grid-view-when-images",
    "page": "category",
    "pageLabel": "Category page",
    "section": "General",
    "checkpoint": "Category page uses relevant category page design (grid view when images are the main decision factor and list view when product attributes are the main decision factor)",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "category-shows-exact-number-of-products-available-on-each-page-either-if-the-pa",
    "page": "category",
    "pageLabel": "Category page",
    "section": "General",
    "checkpoint": "Shows exact number of products available on each page (either if the page is filtered or not)",
    "impact": 2.0,
    "cost": 1.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "category-a-page-description-section-cca-400-words-is-on-top-visually-90-hidden-",
    "page": "category",
    "pageLabel": "Category page",
    "section": "General",
    "checkpoint": "A page description section (cca. 400 words) is on top (visually 90% hidden with \"Read more\") or on the bottom for SEO purposes",
    "impact": 3.0,
    "cost": 3.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "category-you-stay-at-the-same-vertical-position-if-you-go-to-product-page-and-t",
    "page": "category",
    "pageLabel": "Category page",
    "section": "General",
    "checkpoint": "You stay at the same vertical position if you go to product page and then back to category page",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "category-relevant-3-4-products-are-shown-per-row",
    "page": "category",
    "pageLabel": "Category page",
    "section": "Product cards (list)",
    "checkpoint": "Relevant (3-4) products are shown per row",
    "impact": 3.0,
    "cost": 1.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "category-trending-top-rated-and-best-selling-items-are-shown-on-top-of-each-cat",
    "page": "category",
    "pageLabel": "Category page",
    "section": "Product cards (list)",
    "checkpoint": "Trending, top-rated and best-selling items are shown on top of each category by default",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 5,
    "defaultEvaluation": "Can be Improved",
    "tier": "basic"
  },
  {
    "id": "category-additional-product-photos-are-shown-on-mouse-hover",
    "page": "category",
    "pageLabel": "Category page",
    "section": "Product cards (list)",
    "checkpoint": "Additional product photos are shown on mouse hover",
    "impact": 2.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "category-consistent-style-of-images-is-used-for-better-scannability-type-of-ima",
    "page": "category",
    "pageLabel": "Category page",
    "section": "Product cards (list)",
    "checkpoint": "Consistent style of images is used for better scannability (type of images, image background, white space around the products, size of product, angle of photos)",
    "impact": 3.0,
    "cost": 3.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "category-consistent-size-of-product-cards-is-used-for-better-scannability",
    "page": "category",
    "pageLabel": "Category page",
    "section": "Product cards (list)",
    "checkpoint": "Consistent size of product cards is used for better scannability",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "category-the-category-page-clearly-shows-which-product-variants-size-color-are-",
    "page": "category",
    "pageLabel": "Category page",
    "section": "Product cards (list)",
    "checkpoint": "The category page clearly shows which product variants (size, color) are available for each specific product",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 5,
    "defaultEvaluation": "Can be Improved",
    "tier": "basic"
  },
  {
    "id": "category-cta-button-is-shown-to-motivate-users-to-go-look-at-the-product-page-i",
    "page": "category",
    "pageLabel": "Category page",
    "section": "Product cards (list)",
    "checkpoint": "CTA button is shown to motivate users to go look at the product page (ideally on :hover)",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 5,
    "defaultEvaluation": "Can be Improved",
    "tier": "basic"
  },
  {
    "id": "category-scarcity-on-products-that-are-limited-in-stock-is-shown-only-1-left",
    "page": "category",
    "pageLabel": "Category page",
    "section": "Product cards (list)",
    "checkpoint": "Scarcity on products that are limited in stock is shown (\"Only 1 left\")",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Not Relevant",
    "tier": "basic"
  },
  {
    "id": "category-items-out-of-stock-are-shown-you-just-missed-it-so-the-scarcity-above-",
    "page": "category",
    "pageLabel": "Category page",
    "section": "Product cards (list)",
    "checkpoint": "Items out of stock are shown (\"You just missed it\") so the scarcity above is more convincing",
    "impact": 2.0,
    "cost": 3.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "category-badges-on-product-image-thumbnails-are-shown-e-g-fast-delivery-best-se",
    "page": "category",
    "pageLabel": "Category page",
    "section": "Product cards (list)",
    "checkpoint": "Badges on product image thumbnails are shown (e.g. \"Fast delivery\",\"Best-seller\", \"New\", \"Top choice\", \"Trending\")",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "category-category-page-offers-easy-to-understand-and-useful-especially-on-mobil",
    "page": "category",
    "pageLabel": "Category page",
    "section": "Filters",
    "checkpoint": "Category page offers easy to understand and useful (especially on mobile) filters (applicable only for stores with a large number of products)",
    "impact": 3.0,
    "cost": 3.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "category-the-filters-are-prominent-enough-relevant-only-for-stores-where-users-",
    "page": "category",
    "pageLabel": "Category page",
    "section": "Filters",
    "checkpoint": "The filters are prominent enough (relevant only for stores where users are prone to use filters)",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "category-the-most-popular-filters-are-shown-at-the-top-of-the-filters",
    "page": "category",
    "pageLabel": "Category page",
    "section": "Filters",
    "checkpoint": "The most popular filters are shown at the top of the filters",
    "impact": 2.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "category-only-relevant-filters-are-shown-for-each-category-e-g-screen-size-for-",
    "page": "category",
    "pageLabel": "Category page",
    "section": "Filters",
    "checkpoint": "Only relevant filters are shown for each category (e.g. screen size for \"Monitors\" category)",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "category-it-is-clearly-visible-especially-on-mobile-that-filters-are-applied-ho",
    "page": "category",
    "pageLabel": "Category page",
    "section": "Filters",
    "checkpoint": "It is clearly visible (especially on mobile) that filters are applied, how many there are and can be easily removed",
    "impact": 3.0,
    "cost": 3.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "category-users-can-select-multiple-filters-at-once",
    "page": "category",
    "pageLabel": "Category page",
    "section": "Filters",
    "checkpoint": "Users can select multiple filters at once",
    "impact": 3.0,
    "cost": 3.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "category-filters-are-shown-in-a-standard-position-on-the-left-or-on-top-below-t",
    "page": "category",
    "pageLabel": "Category page",
    "section": "Filters",
    "checkpoint": "Filters are shown in a standard position on the left or on top (below the category name)",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "category-when-a-filter-is-selected-the-category-page-auto-updates-in-real-time-",
    "page": "category",
    "pageLabel": "Category page",
    "section": "Filters",
    "checkpoint": "When a filter is selected, the category page auto-updates in real-time (ajax)",
    "impact": 3.0,
    "cost": 3.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "category-product-filters-are-sticky-and-can-be-easily-accessed-at-any-given-mom",
    "page": "category",
    "pageLabel": "Category page",
    "section": "Filters",
    "checkpoint": "Product filters are sticky and can be easily accessed at any given moment",
    "impact": 2.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "category-relevant-selectors-are-used-for-different-types-of-filters-e-g-color-s",
    "page": "category",
    "pageLabel": "Category page",
    "section": "Filters",
    "checkpoint": "Relevant selectors are used for different types of filters (e.g. color swatches instead of \"blue\", price range slider where users can type in the minimum and maximum price insted of a pre-made list of price ranges)",
    "impact": 3.0,
    "cost": 3.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "product-sticky-navigation-with-product-name-product-image-product-page-section",
    "page": "product",
    "pageLabel": "Product page",
    "section": "General",
    "checkpoint": "Sticky navigation with product name, product image, product page sections, availability, old price, new price, discount and CTA that hides when the user is scrolling down but reappears when the user scrolls up",
    "impact": 3.0,
    "cost": 3.0,
    "priorityScore": 5.4,
    "defaultEvaluation": "Bad",
    "tier": "basic"
  },
  {
    "id": "product-product-page-has-an-option-for-potential-customers-to-ask-questions-e-",
    "page": "product",
    "pageLabel": "Product page",
    "section": "General",
    "checkpoint": "Product page has an option for potential customers to ask questions (e.g. live chat, phone number)",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 5,
    "defaultEvaluation": "Can be Improved",
    "tier": "basic"
  },
  {
    "id": "product-product-page-contains-breadcrumbs-not-applicable-to-single-product-sto",
    "page": "product",
    "pageLabel": "Product page",
    "section": "General",
    "checkpoint": "Product page contains breadcrumbs (not applicable to single product stores and direct-response landing pages)",
    "impact": 3.0,
    "cost": 3.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "product-a-customer-can-give-their-email-address-if-the-product-is-currently-no",
    "page": "product",
    "pageLabel": "Product page",
    "section": "General",
    "checkpoint": "A customer can give their email address if the product is currently not available; they will be notified when it becomes available",
    "impact": 3.0,
    "cost": 3.0,
    "priorityScore": 5.4,
    "defaultEvaluation": "Bad",
    "tier": "basic"
  },
  {
    "id": "product-clicking-the-back-button-always-takes-the-user-back-to-the-page-the-us",
    "page": "product",
    "pageLabel": "Product page",
    "section": "General",
    "checkpoint": "Clicking the back button always takes the user back to the page the user came from",
    "impact": 3.0,
    "cost": 3.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "product-product-titles-are-descriptive",
    "page": "product",
    "pageLabel": "Product page",
    "section": "Product overview (above the CTA area)",
    "checkpoint": "Product titles are descriptive",
    "impact": 3.0,
    "cost": 1.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "product-the-main-product-title-is-visually-prominent-compared-to-other-content",
    "page": "product",
    "pageLabel": "Product page",
    "section": "Product overview (above the CTA area)",
    "checkpoint": "The main product title is visually prominent compared to other content",
    "impact": 3.0,
    "cost": 1.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "product-the-product-title-is-under-65-characters-so-it-appears-fully-in-google",
    "page": "product",
    "pageLabel": "Product page",
    "section": "Product overview (above the CTA area)",
    "checkpoint": "The product title is under 65 characters so it appears fully in Google search results",
    "impact": 2.0,
    "cost": 1.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "product-the-product-subtitle-highlight-key-product-benefit-and-contain-power-w",
    "page": "product",
    "pageLabel": "Product page",
    "section": "Product overview (above the CTA area)",
    "checkpoint": "The product subtitle highlight key product benefit and contain power words, e.g. effortless, incredible, absolute, unique, secret, now, new, exclusive, how to, why",
    "impact": 3.0,
    "cost": 1.0,
    "priorityScore": 6,
    "defaultEvaluation": "Can be Improved",
    "tier": "basic"
  },
  {
    "id": "product-product-rating-overviews-are-shown-near-product-titles-that-are-linked",
    "page": "product",
    "pageLabel": "Product page",
    "section": "Product overview (above the CTA area)",
    "checkpoint": "Product rating overviews are shown near product titles that are linked (with click & scroll) to product reviews (e.g. 4.6, Read 5 Reviews)",
    "impact": 3.0,
    "cost": 1.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "product-a-short-list-of-other-key-benefits-of-the-product-is-near-the-main-tit",
    "page": "product",
    "pageLabel": "Product page",
    "section": "Product overview (above the CTA area)",
    "checkpoint": "A short list of other key benefits of the product is near the main title and linked to a detailed description (with green check arrows)",
    "impact": 3.0,
    "cost": 1.0,
    "priorityScore": 6,
    "defaultEvaluation": "Can be Improved",
    "tier": "basic"
  },
  {
    "id": "product-the-main-product-photo-is-attractive",
    "page": "product",
    "pageLabel": "Product page",
    "section": "Image gallery",
    "checkpoint": "The main product photo is attractive",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "product-the-main-product-photo-allows-a-user-to-zoom-in-easily-especially-on-m",
    "page": "product",
    "pageLabel": "Product page",
    "section": "Image gallery",
    "checkpoint": "The main product photo allows a user to zoom in easily (especially on mobile)",
    "impact": 2.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "product-there-is-a-gallery-with-different-product-photos",
    "page": "product",
    "pageLabel": "Product page",
    "section": "Image gallery",
    "checkpoint": "There is a gallery with different product photos",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "product-the-product-gallery-shows-thumbnails-of-other-available-images",
    "page": "product",
    "pageLabel": "Product page",
    "section": "Image gallery",
    "checkpoint": "The product gallery shows thumbnails of other available images",
    "impact": 3.0,
    "cost": 3.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "product-the-product-gallery-contains-product-videos",
    "page": "product",
    "pageLabel": "Product page",
    "section": "Image gallery",
    "checkpoint": "The product gallery contains product videos",
    "impact": 3.0,
    "cost": 3.0,
    "priorityScore": 4,
    "defaultEvaluation": "Can be Improved",
    "tier": "basic"
  },
  {
    "id": "product-the-product-gallery-contains-arrows-to-navigate-between-images",
    "page": "product",
    "pageLabel": "Product page",
    "section": "Image gallery",
    "checkpoint": "The product gallery contains arrows to navigate between images",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "product-the-product-gallery-supports-swipe-actions-on-mobile-devices",
    "page": "product",
    "pageLabel": "Product page",
    "section": "Image gallery",
    "checkpoint": "The product gallery supports swipe actions on mobile devices",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "product-there-are-images-for-different-product-variants-sizes",
    "page": "product",
    "pageLabel": "Product page",
    "section": "Image gallery",
    "checkpoint": "There are images for different product variants/sizes",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "product-the-main-cta-is-the-most-visible-element-on-the-product-page-and-conta",
    "page": "product",
    "pageLabel": "Product page",
    "section": "CTA area",
    "checkpoint": "The main CTA is the most visible element on the product page and contains the \"cart\" icon",
    "impact": 3.0,
    "cost": 1.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "product-product-variants-are-easily-accessible-on-mobile-and-big-enough-with-e",
    "page": "product",
    "pageLabel": "Product page",
    "section": "CTA area",
    "checkpoint": "Product variants are easily accessible on mobile and big enough with enough white space around to prevent misclicks",
    "impact": 3.0,
    "cost": 1.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "product-the-product-variant-selection-is-connected-with-the-product-gallery-an",
    "page": "product",
    "pageLabel": "Product page",
    "section": "CTA area",
    "checkpoint": "The product variant selection is connected with the product gallery and shows images of chosen product variants",
    "impact": 3.0,
    "cost": 1.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "product-a-visible-reminder-is-included-to-select-size-color-if-a-customer-forg",
    "page": "product",
    "pageLabel": "Product page",
    "section": "CTA area",
    "checkpoint": "A visible reminder is included to select size/color if a customer forgets and clicks \"add to cart\" too early",
    "impact": 3.0,
    "cost": 1.0,
    "priorityScore": 0,
    "defaultEvaluation": "Not Relevant",
    "tier": "basic"
  },
  {
    "id": "product-interactive-selectors-are-used-for-product-variants-the-gallery-image-",
    "page": "product",
    "pageLabel": "Product page",
    "section": "CTA area",
    "checkpoint": "Interactive selectors are used for product variants (the gallery image and the price are changed in real-time, without triggering a page reload)",
    "impact": 3.0,
    "cost": 1.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "product-a-size-chart-or-link-that-opens-in-a-small-popup-and-is-easily-closed-",
    "page": "product",
    "pageLabel": "Product page",
    "section": "CTA area",
    "checkpoint": "A size chart (or link that opens in a small popup and is easily closed on mobile) is provided near the size selections (for products with different sizes)",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "product-localized-units-for-products-are-shown-with-different-sizes-measuremen",
    "page": "product",
    "pageLabel": "Product page",
    "section": "CTA area",
    "checkpoint": "Localized units for products are shown with different sizes/measurements (e.g. cm, inches, kg)",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Not Relevant",
    "tier": "basic"
  },
  {
    "id": "product-product-descriptions-mention-the-size-of-the-model-and-the-size-of-the",
    "page": "product",
    "pageLabel": "Product page",
    "section": "CTA area",
    "checkpoint": "Product descriptions mention the size of the model and the size of the shirt the model is wearing (only for apparel)",
    "impact": 3.0,
    "cost": 1.0,
    "priorityScore": 0,
    "defaultEvaluation": "Not Relevant",
    "tier": "basic"
  },
  {
    "id": "product-interactive-selectors-are-used-for-quantity-selection-instead-of-dropd",
    "page": "product",
    "pageLabel": "Product page",
    "section": "CTA area",
    "checkpoint": "Interactive selectors are used for quantity selection instead of dropdowns (the price and quantity are changed in real-time, without triggering a page reload)",
    "impact": 2.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "product-the-cta-copy-clearly-explains-what-will-happen-when-you-click-on-it-e-",
    "page": "product",
    "pageLabel": "Product page",
    "section": "CTA area",
    "checkpoint": "The CTA copy clearly explains what will happen when you click on it (e.g. Proceed to secure checkout)",
    "impact": 3.0,
    "cost": 1.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "product-clear-feedback-is-provided-once-the-product-has-been-added-to-the-cart",
    "page": "product",
    "pageLabel": "Product page",
    "section": "CTA area",
    "checkpoint": "Clear feedback is provided once the product has been added to the cart (e.g. a number in the mini-cart widget increases)",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "product-the-main-cta-change-states-once-users-add-a-product-to-the-cart-e-g-ch",
    "page": "product",
    "pageLabel": "Product page",
    "section": "CTA area",
    "checkpoint": "The main CTA change states once users add a product to the cart (e.g. \"[check arrow] Product added to your cart\" and after 2 seconds \"Go to my shopping cart [right arrow]\")",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "product-the-price-of-the-product-is-prominent-enough-especially-if-it-s-discou",
    "page": "product",
    "pageLabel": "Product page",
    "section": "CTA area",
    "checkpoint": "The price of the product is prominent enough, especially if it's discounted",
    "impact": 3.0,
    "cost": 1.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "product-the-price-of-the-product-is-placed-near-the-main-cta",
    "page": "product",
    "pageLabel": "Product page",
    "section": "CTA area",
    "checkpoint": "The price of the product is placed near the main CTA",
    "impact": 3.0,
    "cost": 1.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "product-the-price-of-the-product-is-localized",
    "page": "product",
    "pageLabel": "Product page",
    "section": "CTA area",
    "checkpoint": "The price of the product is localized",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "product-the-background-color-of-the-product-s-primary-cta-differs-from-other-e",
    "page": "product",
    "pageLabel": "Product page",
    "section": "CTA area",
    "checkpoint": "The background color of the product's primary CTA differs from other elements (e.g. slightly grey)",
    "impact": 2.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "product-all-additional-charges-that-may-apply-are-shown-near-the-main-cta-e-g-",
    "page": "product",
    "pageLabel": "Product page",
    "section": "CTA area",
    "checkpoint": "All additional charges that may apply are shown near the main CTA (e.g. additional shipping costs due to product size, VAT)",
    "impact": 3.0,
    "cost": 3.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "product-if-free-shipping-is-offered-it-s-highlighted-near-the-main-cta",
    "page": "product",
    "pageLabel": "Product page",
    "section": "CTA area",
    "checkpoint": "If free shipping is offered, it's highlighted near the main CTA",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "product-all-shipping-information-is-shown-near-the-main-cta-delivery-to-shoppe",
    "page": "product",
    "pageLabel": "Product page",
    "section": "CTA area",
    "checkpoint": "All shipping information is shown near the main CTA (delivery to shopper's location, shopper's country flag, cost, time)",
    "impact": 3.0,
    "cost": 3.0,
    "priorityScore": 4,
    "defaultEvaluation": "Can be Improved",
    "tier": "basic"
  },
  {
    "id": "product-availability-of-the-product-is-shown-near-the-main-cta-e-g-in-stock",
    "page": "product",
    "pageLabel": "Product page",
    "section": "CTA area",
    "checkpoint": "Availability of the product is shown near the main CTA (e.g. \"In stock\")",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "product-the-old-price-with-a-strike-trough-is-shown-with-the-new-price-and-how",
    "page": "product",
    "pageLabel": "Product page",
    "section": "CTA area",
    "checkpoint": "The old price (with a strike-trough) is shown with the new price and how much shoppers will save (% or $) when the product is on sale",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 5,
    "defaultEvaluation": "Can be Improved",
    "tier": "basic"
  },
  {
    "id": "product-clear-information-is-shown-about-returns-refunds-and-money-back-guaran",
    "page": "product",
    "pageLabel": "Product page",
    "section": "CTA area",
    "checkpoint": "Clear information is shown about returns, refunds and money-back guarantee",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 5,
    "defaultEvaluation": "Can be Improved",
    "tier": "basic"
  },
  {
    "id": "product-express-payment-options-are-shown-and-available-that-are-commonly-used",
    "page": "product",
    "pageLabel": "Product page",
    "section": "CTA area",
    "checkpoint": "Express payment options are shown and available that are commonly used (e.g. PayPal, Amazon, Google Pay, Apple Pay). Useful for direct-response landing pages",
    "impact": 3.0,
    "cost": 3.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "product-there-is-an-option-for-a-payment-with-installments-e-g-klarna-afterpay",
    "page": "product",
    "pageLabel": "Product page",
    "section": "CTA area",
    "checkpoint": "There is an option for a payment with installments (e.g. Klarna, AfterPay; for expensive products only). Useful for direct-response landing pages that don't encourage the user to add other products to the cart",
    "impact": 3.0,
    "cost": 3.0,
    "priorityScore": 0,
    "defaultEvaluation": "Not Relevant",
    "tier": "basic"
  },
  {
    "id": "product-product-page-highlights-logos-of-news-sites-blogs-celebrities-where-th",
    "page": "product",
    "pageLabel": "Product page",
    "section": "Social proof",
    "checkpoint": "Product page highlights logos of news sites/blogs/celebrities where the product/brand has had PR exposure (e.g. \"Used by executives at Fortune 500\" )",
    "impact": 3.0,
    "cost": 1.0,
    "priorityScore": 6,
    "defaultEvaluation": "Can be Improved",
    "tier": "basic"
  },
  {
    "id": "product-customer-reviews-are-shown-with-a-review-title-customer-photos-of-prod",
    "page": "product",
    "pageLabel": "Product page",
    "section": "Social proof",
    "checkpoint": "Customer reviews are shown with a review title, customer photos of product, star rating, photo of reviewer, name and last name, \"verified\" buyer, occupation, and age",
    "impact": 3.0,
    "cost": 3.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "product-customer-reviews-visually-stand-out-from-other-content-ideally-on-a-sl",
    "page": "product",
    "pageLabel": "Product page",
    "section": "Social proof",
    "checkpoint": "Customer reviews visually stand out from other content (ideally on a slightly yellow background)",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "product-product-page-contains-photos-with-faces-of-how-happy-customers-are-usi",
    "page": "product",
    "pageLabel": "Product page",
    "section": "Social proof",
    "checkpoint": "Product page contains photos (with faces) of how (happy) customers are using the product",
    "impact": 3.0,
    "cost": 3.0,
    "priorityScore": 5.4,
    "defaultEvaluation": "Bad",
    "tier": "basic"
  },
  {
    "id": "product-product-overall-star-ratings-are-shown-and-can-be-filtered-by-the-star",
    "page": "product",
    "pageLabel": "Product page",
    "section": "Social proof",
    "checkpoint": "Product overall star ratings are shown and can be filtered by the star rating",
    "impact": 3.0,
    "cost": 3.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "product-product-page-contains-the-number-of-customers-this-week-month-all-time",
    "page": "product",
    "pageLabel": "Product page",
    "section": "Social proof",
    "checkpoint": "Product page contains the number of customers this week/month/all-time (e.g. \"19,222 products successfully shipped and delivered this month alone\")",
    "impact": 2.0,
    "cost": 2.0,
    "priorityScore": 4,
    "defaultEvaluation": "Can be Improved",
    "tier": "basic"
  },
  {
    "id": "product-product-page-contains-video-testimonials",
    "page": "product",
    "pageLabel": "Product page",
    "section": "Social proof",
    "checkpoint": "Product page contains video testimonials",
    "impact": 3.0,
    "cost": 3.0,
    "priorityScore": 5.4,
    "defaultEvaluation": "Bad",
    "tier": "basic"
  },
  {
    "id": "product-product-page-contains-the-number-of-facebook-and-twitter-followers",
    "page": "product",
    "pageLabel": "Product page",
    "section": "Social proof",
    "checkpoint": "Product page contains the number of Facebook and Twitter followers",
    "impact": 2.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Not Relevant",
    "tier": "basic"
  },
  {
    "id": "product-clear-quantity-discounts-are-offered-near-the-main-cta-1x-24-99-piece-",
    "page": "product",
    "pageLabel": "Product page",
    "section": "Conversion and AOV 'boosters'",
    "checkpoint": "Clear quantity discounts are offered near the main CTA (1x $24.99/piece, [\"Top choice\" badge]; 2x 19,99€/piece, [\"Recommended\" badge]; 3x $17,49/piece, [\"Best value\" badge])",
    "impact": 3.0,
    "cost": 3.0,
    "priorityScore": 0,
    "defaultEvaluation": "Not Relevant",
    "tier": "basic"
  },
  {
    "id": "product-relevant-cross-sell-up-sell-products-are-offered",
    "page": "product",
    "pageLabel": "Product page",
    "section": "Conversion and AOV 'boosters'",
    "checkpoint": "Relevant cross-sell/up-sell products are offered",
    "impact": 3.0,
    "cost": 3.0,
    "priorityScore": 4,
    "defaultEvaluation": "Can be Improved",
    "tier": "basic"
  },
  {
    "id": "product-relevant-bundle-products-are-offered-with-prominent-discounts",
    "page": "product",
    "pageLabel": "Product page",
    "section": "Conversion and AOV 'boosters'",
    "checkpoint": "Relevant bundle products are offered with prominent discounts",
    "impact": 3.0,
    "cost": 3.0,
    "priorityScore": 5.4,
    "defaultEvaluation": "Bad",
    "tier": "basic"
  },
  {
    "id": "product-urgency-triggers-are-used-e-g-today-only-black-friday-offer-free-bonus",
    "page": "product",
    "pageLabel": "Product page",
    "section": "Conversion and AOV 'boosters'",
    "checkpoint": "Urgency triggers are used (e.g. \"Today only\", \"Black Friday offer\", \"Free bonus\", \"If order is placed in the next 12 min, it will be shipped today\") near the main CTA",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Not Relevant",
    "tier": "basic"
  },
  {
    "id": "product-scarcity-triggers-are-used-e-g-only-3-products-left-near-the-main-cta",
    "page": "product",
    "pageLabel": "Product page",
    "section": "Conversion and AOV 'boosters'",
    "checkpoint": "Scarcity triggers are used (e.g. \"Only 3 products left\") near the main CTA",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "product-customers-are-shown-how-many-people-have-viewed-and-bought-the-product",
    "page": "product",
    "pageLabel": "Product page",
    "section": "Conversion and AOV 'boosters'",
    "checkpoint": "Customers are shown how many people have viewed and bought the product in the last 24 hours",
    "impact": 3.0,
    "cost": 3.0,
    "priorityScore": 5.4,
    "defaultEvaluation": "Bad",
    "tier": "basic"
  },
  {
    "id": "product-a-store-is-giving-away-a-small-percentage-of-the-profit-to-charity-and",
    "page": "product",
    "pageLabel": "Product page",
    "section": "Conversion and AOV 'boosters'",
    "checkpoint": "A store is giving away a small percentage of the profit to charity; and highlights this information",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 5,
    "defaultEvaluation": "Can be Improved",
    "tier": "basic"
  },
  {
    "id": "product-the-product-page-contains-visitors-who-viewed-this-product-also-viewed",
    "page": "product",
    "pageLabel": "Product page",
    "section": "Conversion and AOV 'boosters'",
    "checkpoint": "The product page contains \"Visitors who viewed this product also viewed...\" where users are shown complementary OR/AND alternative products",
    "impact": 3.0,
    "cost": 3.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "product-the-product-description-is-easy-to-read-font-size-contrast-single-colu",
    "page": "product",
    "pageLabel": "Product page",
    "section": "Product description",
    "checkpoint": "The product description is easy to read (font size, contrast, single column, 75 characters per line, line-height 1.5, max. 4 lines long)",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "product-product-information-structure-is-easy-to-scan-grouped-information-bull",
    "page": "product",
    "pageLabel": "Product page",
    "section": "Product description",
    "checkpoint": "Product information structure is easy to scan (grouped information, bullet points, important benefits highlighted)",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "product-the-sections-of-the-page-general-technical-info-are-grouped-together-i",
    "page": "product",
    "pageLabel": "Product page",
    "section": "Product description",
    "checkpoint": "The sections of the page (\"General\", \"Technical info\") are grouped together in accordion (if they are longer) and scannable on mobile",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Not Relevant",
    "tier": "basic"
  },
  {
    "id": "product-section-titles-explain-benefits-and-not-features-of-the-product",
    "page": "product",
    "pageLabel": "Product page",
    "section": "Product description",
    "checkpoint": "Section titles explain benefits (and not features) of the product",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 5,
    "defaultEvaluation": "Can be Improved",
    "tier": "basic"
  },
  {
    "id": "product-customers-are-shown-all-the-things-that-are-included-in-the-product-id",
    "page": "product",
    "pageLabel": "Product page",
    "section": "Product description",
    "checkpoint": "Customers are shown all the things that are included in the product (ideally with an included photo)",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Not Relevant",
    "tier": "basic"
  },
  {
    "id": "product-product-page-contains-customer-faqs-for-each-specific-product-as-well-",
    "page": "product",
    "pageLabel": "Product page",
    "section": "Product description",
    "checkpoint": "Product page contains customer FAQs (for each specific product as well as store-wide questions)",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 6.7,
    "defaultEvaluation": "Bad",
    "tier": "basic"
  },
  {
    "id": "product-the-table-of-technical-specifications-is-readable-different-colors-of-",
    "page": "product",
    "pageLabel": "Product page",
    "section": "Product description",
    "checkpoint": "The table of technical specifications is readable (different colors of lines, hover state of the line, not too far apart)",
    "impact": 2.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Not Relevant",
    "tier": "basic"
  },
  {
    "id": "product-product-page-offers-product-comparisons",
    "page": "product",
    "pageLabel": "Product page",
    "section": "Product description",
    "checkpoint": "Product page offers product comparisons",
    "impact": 3.0,
    "cost": 3.0,
    "priorityScore": 5.4,
    "defaultEvaluation": "Bad",
    "tier": "basic"
  },
  {
    "id": "product-product-description-explains-how-to-use-the-product-in-3-easy-steps",
    "page": "product",
    "pageLabel": "Product page",
    "section": "Product description",
    "checkpoint": "Product description explains how to use the product in 3 easy steps",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Not Relevant",
    "tier": "basic"
  },
  {
    "id": "product-product-page-contains-embedded-reviews-or-screenshots-from-social-netw",
    "page": "product",
    "pageLabel": "Product page",
    "section": "Product description",
    "checkpoint": "Product page contains embedded reviews (or screenshots) from social networks (e.g. Facebook post, Messenger, Whatsapp, Tweet, Instagram post, Instagram PM, Viber, text message)",
    "impact": 3.0,
    "cost": 3.0,
    "priorityScore": 0,
    "defaultEvaluation": "Not Relevant",
    "tier": "basic"
  },
  {
    "id": "product-the-personalization-page-doesn-t-contain-any-designs-to-choose-from-so",
    "page": "product",
    "pageLabel": "Product page",
    "section": "Product description",
    "checkpoint": "The personalization page doesn’t contain any designs to choose from, so customers are unable to personalize their items. https://www.faribaultmill.com/apps/pulse-personalizer/?variantId=41050921533549&handle=frontier-cotton-blanket&quantity=1&returnurl=https%3A%2F%2Fwww.faribaultmill.com%2Fproducts%2Ffrontier-cotton-blanket&sku=1170TWBL%20NAT",
    "impact": null,
    "cost": null,
    "priorityScore": null,
    "defaultEvaluation": "Bad",
    "tier": "basic"
  },
  {
    "id": "cart-the-overall-cart-design-is-clear-and-uncluttered",
    "page": "cart",
    "pageLabel": "Cart page",
    "section": "General",
    "checkpoint": "The overall cart design is clear and uncluttered",
    "impact": 3.0,
    "cost": 3.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "cart-urgency-triggers-are-used-your-items-are-reserved-for-10-minutes-if-yo",
    "page": "cart",
    "pageLabel": "Cart page",
    "section": "General",
    "checkpoint": "Urgency triggers are used (\"Your items are reserved for 10 minutes\", \"If you order in next 12 minutes, the order will be shipped today\")",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 5,
    "defaultEvaluation": "Can be Improved",
    "tier": "basic"
  },
  {
    "id": "cart-the-cart-page-clearly-informs-the-user-how-far-away-they-are-from-the-",
    "page": "cart",
    "pageLabel": "Cart page",
    "section": "General",
    "checkpoint": "The cart page clearly informs the user how far away they are from the threshold for free shipping (or a 3% discount)",
    "impact": 3.0,
    "cost": 3.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "cart-if-the-user-already-reached-the-threshold-for-free-shipping-the-cart-p",
    "page": "cart",
    "pageLabel": "Cart page",
    "section": "General",
    "checkpoint": "If the user already reached the threshold for free shipping, the cart prominently highlights that (e.g. bold, green)",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "cart-when-the-user-returns-to-the-site-the-items-that-they-placed-in-the-ca",
    "page": "cart",
    "pageLabel": "Cart page",
    "section": "General",
    "checkpoint": "When the user returns to the site, the items that they placed in the cart are still there",
    "impact": 3.0,
    "cost": 3.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "cart-all-important-product-information-is-shown-in-the-cart-title-image-cho",
    "page": "cart",
    "pageLabel": "Cart page",
    "section": "General",
    "checkpoint": "All important product information is shown in the cart (title, image, chosen variant, quantity, price)",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "cart-the-right-product-image-is-shown-for-the-chosen-product-variant-e-g-re",
    "page": "cart",
    "pageLabel": "Cart page",
    "section": "General",
    "checkpoint": "The right product image is shown for the chosen product variant (e.g. Red dress)",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "cart-the-cart-allows-you-to-change-the-quantity-of-the-product-and-automati",
    "page": "cart",
    "pageLabel": "Cart page",
    "section": "General",
    "checkpoint": "The cart allows you to change the quantity of the product and automatically updates the cart",
    "impact": 3.0,
    "cost": 3.0,
    "priorityScore": 5.4,
    "defaultEvaluation": "Bad",
    "tier": "basic"
  },
  {
    "id": "cart-the-user-can-easily-remove-an-item-from-the-cart",
    "page": "cart",
    "pageLabel": "Cart page",
    "section": "General",
    "checkpoint": "The user can easily remove an item from the cart",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "cart-the-cart-shows-the-day-of-expected-delivery",
    "page": "cart",
    "pageLabel": "Cart page",
    "section": "General",
    "checkpoint": "The cart shows the day of expected delivery",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Not Relevant",
    "tier": "basic"
  },
  {
    "id": "cart-scarcity-triggers-are-shown-next-to-each-item-only-1-item-in-stock-in-",
    "page": "cart",
    "pageLabel": "Cart page",
    "section": "General",
    "checkpoint": "Scarcity triggers are shown next to each item (\"Only 1 item in stock\") in a prominent color (e.g. red, orange)",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Not Relevant",
    "tier": "basic"
  },
  {
    "id": "cart-the-cart-offers-an-easy-way-to-get-in-touch-with-the-store-s-help-cent",
    "page": "cart",
    "pageLabel": "Cart page",
    "section": "General",
    "checkpoint": "The cart offers an easy way to get in touch with the store's help center (e.g. live chat, email, phone number)",
    "impact": 3.0,
    "cost": 1.0,
    "priorityScore": 6,
    "defaultEvaluation": "Can be Improved",
    "tier": "basic"
  },
  {
    "id": "cart-information-about-returns-refunds-and-a-money-back-guarantee-is-shown-",
    "page": "cart",
    "pageLabel": "Cart page",
    "section": "General",
    "checkpoint": "Information about returns, refunds and a money-back guarantee is shown (if on external pages, a small pop-up window appears instead of redirecting the customer away from the cart)",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 5,
    "defaultEvaluation": "Can be Improved",
    "tier": "basic"
  },
  {
    "id": "cart-the-cart-offers-a-way-to-enter-a-coupon-code-but-with-a-hidden-input-f",
    "page": "cart",
    "pageLabel": "Cart page",
    "section": "General",
    "checkpoint": "The cart offers a way to enter a coupon code but with a hidden input field (so users won't go searching for coupon codes on Google)",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Not Relevant",
    "tier": "basic"
  },
  {
    "id": "cart-the-cart-offers-inexpensive-upsell-cross-sell-products-with-benefits-a",
    "page": "cart",
    "pageLabel": "Cart page",
    "section": "General",
    "checkpoint": "The cart offers (inexpensive) upsell/cross-sell products with benefits and urgency (\"Now or never\") and a special discount (e.g. 50% OFF)",
    "impact": 3.0,
    "cost": 3.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "cart-customers-can-save-products-cart-for-later-instead-of-deleting-them",
    "page": "cart",
    "pageLabel": "Cart page",
    "section": "General",
    "checkpoint": "Customers can “save products / cart for later” instead of deleting them",
    "impact": 2.0,
    "cost": 3.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "cart-the-subtotal-price-is-prominent-and-placed-near-the-main-cta",
    "page": "cart",
    "pageLabel": "Cart page",
    "section": "CTA area",
    "checkpoint": "The subtotal price is prominent and placed near the main CTA",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "cart-estimated-taxes-are-shown",
    "page": "cart",
    "pageLabel": "Cart page",
    "section": "CTA area",
    "checkpoint": "Estimated taxes are shown",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "cart-the-shopper-is-shown-how-much-they-will-save-on-their-entire-purchase-",
    "page": "cart",
    "pageLabel": "Cart page",
    "section": "CTA area",
    "checkpoint": "The shopper is shown how much they will save on their entire purchase near main CTA",
    "impact": 3.0,
    "cost": 1.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "cart-the-main-cta-includes-what-will-happen-next-proceed-to-a-secure-checko",
    "page": "cart",
    "pageLabel": "Cart page",
    "section": "CTA area",
    "checkpoint": "The main CTA includes what will happen next (\"Proceed to a secure checkout\") and is the most prominent element and duplicated at the top and bottom of the page",
    "impact": 3.0,
    "cost": 1.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "cart-the-main-cta-proceed-to-a-secure-checkout-includes-a-lock-icon-on-a-di",
    "page": "cart",
    "pageLabel": "Cart page",
    "section": "CTA area",
    "checkpoint": "The main CTA (\"Proceed to a secure checkout\") includes a lock icon on a distinctive (gray) background",
    "impact": 2.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "cart-below-the-main-cta-is-a-trust-icon-seal-badge-e-g-verified-by-norton-a",
    "page": "cart",
    "pageLabel": "Cart page",
    "section": "CTA area",
    "checkpoint": "Below the main CTA is a trust icon / seal badge (e.g. verified by Norton) along with reassuring copy \"Shop with confidence\"",
    "impact": 3.0,
    "cost": 1.0,
    "priorityScore": 6,
    "defaultEvaluation": "Can be Improved",
    "tier": "basic"
  },
  {
    "id": "cart-alternative-payment-options-are-shown-below-the-main-cta-button-e-g-pa",
    "page": "cart",
    "pageLabel": "Cart page",
    "section": "CTA area",
    "checkpoint": "Alternative payment options are shown below the main CTA button (e.g. PayPal, Amazon Pay, Google Pay)",
    "impact": 3.0,
    "cost": 3.0,
    "priorityScore": 0,
    "defaultEvaluation": "Not Relevant",
    "tier": "basic"
  },
  {
    "id": "cart-images-of-all-available-installment-methods-are-shown-e-g-klarna-with-",
    "page": "cart",
    "pageLabel": "Cart page",
    "section": "CTA area",
    "checkpoint": "Images of all available installment methods are shown (e.g. Klarna) with clear monthly payment and duration info (especially useful for more expensive products)",
    "impact": 3.0,
    "cost": 3.0,
    "priorityScore": 0,
    "defaultEvaluation": "Not Relevant",
    "tier": "basic"
  },
  {
    "id": "cart-a-secondary-cta-continue-shopping-button-is-available-on-the-cart-page",
    "page": "cart",
    "pageLabel": "Cart page",
    "section": "CTA area",
    "checkpoint": "A secondary CTA \"Continue shopping\" button is available on the cart page",
    "impact": 2.0,
    "cost": 1.0,
    "priorityScore": 5,
    "defaultEvaluation": "Can be Improved",
    "tier": "basic"
  },
  {
    "id": "checkout-the-checkout-allows-the-user-to-make-a-purchase-as-a-guest-avoids-unne",
    "page": "checkout",
    "pageLabel": "Checkout page",
    "section": "General",
    "checkpoint": "The checkout allows the user to make a purchase as a guest (avoids unnecessary registration)",
    "impact": 3.0,
    "cost": 3.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "checkout-if-there-is-a-multi-step-checkout-it-s-clear-what-will-happen-after-yo",
    "page": "checkout",
    "pageLabel": "Checkout page",
    "section": "General",
    "checkpoint": "If there is a multi-step checkout, it's clear what will happen after you click CTA",
    "impact": 3.0,
    "cost": 1.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "checkout-the-form-avoids-making-the-user-start-again-if-there-s-an-error",
    "page": "checkout",
    "pageLabel": "Checkout page",
    "section": "General",
    "checkpoint": "The form avoids making the user start again if there's an error",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "checkout-immediately-prior-to-commiting-to-the-purchase-the-site-shows-the-user",
    "page": "checkout",
    "pageLabel": "Checkout page",
    "section": "General",
    "checkpoint": "Immediately prior to commiting to the purchase, the site shows the user a clear order summary",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "checkout-below-the-main-cta-is-a-trust-icon-seal-badge-e-g-verified-by-norton-a",
    "page": "checkout",
    "pageLabel": "Checkout page",
    "section": "General",
    "checkpoint": "Below the main CTA is a trust icon / seal badge (e.g. verified by Norton) along with reasurring copy \"Shop with confidence\"",
    "impact": 3.0,
    "cost": 1.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "checkout-checkout-doesn-t-contain-any-outgoing-links-e-g-clickable-logo-navigat",
    "page": "checkout",
    "pageLabel": "Checkout page",
    "section": "General",
    "checkpoint": "Checkout doesn't contain any outgoing links (e.g. clickable logo, navigation and footer)",
    "impact": 3.0,
    "cost": 1.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "checkout-the-site-s-privacy-policy-is-easy-to-find-especially-on-pages-that-ask",
    "page": "checkout",
    "pageLabel": "Checkout page",
    "section": "General",
    "checkpoint": "The site's privacy policy is easy to find, especially on pages that ask for personal information, and the policy is simple and clear",
    "impact": 2.0,
    "cost": 1.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "checkout-checkout-offers-an-easy-way-to-get-in-touch-with-the-store-s-help-cent",
    "page": "checkout",
    "pageLabel": "Checkout page",
    "section": "General",
    "checkpoint": "Checkout offers an easy way to get in touch with the store's help center (e.g. live chat, email, phone number)",
    "impact": 3.0,
    "cost": 1.0,
    "priorityScore": 6,
    "defaultEvaluation": "Can be Improved",
    "tier": "basic"
  },
  {
    "id": "checkout-the-main-cta-is-the-most-prominent-element-on-the-checkout-page",
    "page": "checkout",
    "pageLabel": "Checkout page",
    "section": "General",
    "checkpoint": "The main CTA is the most prominent element on the checkout page",
    "impact": 3.0,
    "cost": 1.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "checkout-after-the-checkout-page-and-before-the-thank-you-page-there-is-an-upse",
    "page": "checkout",
    "pageLabel": "Checkout page",
    "section": "Conversion and AOV 'boosters'",
    "checkpoint": "After the checkout page and before the thank you page, there is an upsell step where user can add another product to the existing order",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 5,
    "defaultEvaluation": "Can be Improved",
    "tier": "basic"
  },
  {
    "id": "checkout-the-checkout-page-contains-order-bumps-e-g-skip-the-queue-urgent-shipp",
    "page": "checkout",
    "pageLabel": "Checkout page",
    "section": "Conversion and AOV 'boosters'",
    "checkpoint": "The checkout page contains order bumps (e.g. \"Skip the queue\", \"Urgent shipping\", \"Gift packaging\", \"Package insurance\" with prices under $3)",
    "impact": 3.0,
    "cost": 3.0,
    "priorityScore": 0,
    "defaultEvaluation": "Not Relevant",
    "tier": "basic"
  },
  {
    "id": "checkout-urgency-triggers-are-used-your-items-are-reserved-for-10-minutes-if-yo",
    "page": "checkout",
    "pageLabel": "Checkout page",
    "section": "Conversion and AOV 'boosters'",
    "checkpoint": "Urgency triggers are used (\"Your items are reserved for 10 minutes\", \"If your order is completed in the next 12 minutes, it will be shipped today\")",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Not Relevant",
    "tier": "basic"
  },
  {
    "id": "checkout-log-in-and-registration",
    "page": "checkout",
    "pageLabel": "Checkout page",
    "section": "Conversion and AOV 'boosters'",
    "checkpoint": "Log in and registration",
    "impact": null,
    "cost": null,
    "priorityScore": null,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "checkout-checkout-allows-users-to-log-in-so-they-don-t-need-to-type-in-all-the-",
    "page": "checkout",
    "pageLabel": "Checkout page",
    "section": "Conversion and AOV 'boosters'",
    "checkpoint": "Checkout allows users to log in so they don't need to type in all the information again",
    "impact": 3.0,
    "cost": 3.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "checkout-during-registration-the-password-selection-process-is-not-overcomplica",
    "page": "checkout",
    "pageLabel": "Checkout page",
    "section": "Conversion and AOV 'boosters'",
    "checkpoint": "During registration, the password selection process is not overcomplicated with unnecessary requirements",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "checkout-password-recovery-is-easy",
    "page": "checkout",
    "pageLabel": "Checkout page",
    "section": "Conversion and AOV 'boosters'",
    "checkpoint": "Password recovery is easy",
    "impact": 3.0,
    "cost": 3.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "checkout-forms",
    "page": "checkout",
    "pageLabel": "Checkout page",
    "section": "Conversion and AOV 'boosters'",
    "checkpoint": "Forms",
    "impact": null,
    "cost": null,
    "priorityScore": null,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "checkout-the-layout-of-input-fields-is-as-simple-as-possible-single-column-idea",
    "page": "checkout",
    "pageLabel": "Checkout page",
    "section": "Conversion and AOV 'boosters'",
    "checkpoint": "The layout of input fields is as simple as possible (single column, ideally)",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "checkout-the-checkout-page-has-the-minimum-amount-of-input-fields-needed-for-co",
    "page": "checkout",
    "pageLabel": "Checkout page",
    "section": "Conversion and AOV 'boosters'",
    "checkpoint": "The checkout page has the minimum amount of input fields needed for completing the purchase",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "checkout-the-checkout-page-input-fields-are-floating-labels-so-the-user-can-see",
    "page": "checkout",
    "pageLabel": "Checkout page",
    "section": "Conversion and AOV 'boosters'",
    "checkpoint": "The checkout page input fields are \"floating labels\" so the user can see the name of the field and its contents simultaneously",
    "impact": 3.0,
    "cost": 3.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "checkout-the-user-s-email-address-is-requested-first-so-in-case-they-leave-the-",
    "page": "checkout",
    "pageLabel": "Checkout page",
    "section": "Conversion and AOV 'boosters'",
    "checkpoint": "The user's email address is requested first so in case they leave the checkout, the store is able to contact them",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "checkout-the-input-fields-contain-suggestions-email-e-g-john-doe-gmail-com-to-d",
    "page": "checkout",
    "pageLabel": "Checkout page",
    "section": "Conversion and AOV 'boosters'",
    "checkpoint": "The input fields contain suggestions (Email: e.g. john.doe@gmail.com) to decrease the user's cognitive load",
    "impact": 3.0,
    "cost": 1.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "checkout-the-checkout-page-has-an-option-to-check-the-billing-address-is-the-sa",
    "page": "checkout",
    "pageLabel": "Checkout page",
    "section": "Conversion and AOV 'boosters'",
    "checkpoint": "The checkout page has an option to check \"the billing address is the same as shipping\", so the user doesn't need to enter the same address twice",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "checkout-choosing-a-payment-option-e-g-radio-buttons-is-easily-accessible-on-mo",
    "page": "checkout",
    "pageLabel": "Checkout page",
    "section": "Conversion and AOV 'boosters'",
    "checkpoint": "Choosing a payment option (e.g. radio buttons) is easily accessible on mobile",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "checkout-visual-prompts-are-included-for-credit-card-details-such-as-an-image-o",
    "page": "checkout",
    "pageLabel": "Checkout page",
    "section": "Conversion and AOV 'boosters'",
    "checkpoint": "Visual prompts are included for credit card details, such as an image of where to find the CVV code",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "checkout-credit-card-input-fields-are-shown-on-a-gray-background-for-higher-per",
    "page": "checkout",
    "pageLabel": "Checkout page",
    "section": "Conversion and AOV 'boosters'",
    "checkpoint": "Credit card input fields are shown on a gray background for higher (perceived) trust ",
    "impact": 3.0,
    "cost": 1.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "checkout-users-can-easily-jump-between-input-fields-of-a-form-by-using-the-tab-",
    "page": "checkout",
    "pageLabel": "Checkout page",
    "section": "Conversion and AOV 'boosters'",
    "checkpoint": "Users can easily jump between input fields of a form by using the \"Tab\" key",
    "impact": 1.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "checkout-when-entering-data-into-a-number-only-input-field-e-g-post-code-phone-",
    "page": "checkout",
    "pageLabel": "Checkout page",
    "section": "Conversion and AOV 'boosters'",
    "checkpoint": "When entering data into a number-only input field (e.g. post code, phone number), a numeric keyboard is shown on mobile",
    "impact": 2.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "checkout-when-entering-an-email-a-keyboard-with-dedicated-buttons-for-and-com-i",
    "page": "checkout",
    "pageLabel": "Checkout page",
    "section": "Conversion and AOV 'boosters'",
    "checkpoint": "When entering an email, a keyboard with dedicated buttons for @ and \".com\" is shown on mobile",
    "impact": 2.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "checkout-input-field-width-indicates-the-amount-and-format-of-data-that-needs-t",
    "page": "checkout",
    "pageLabel": "Checkout page",
    "section": "Conversion and AOV 'boosters'",
    "checkpoint": "Input-field width indicates the amount and format of data that needs to be entered (e.g. postal code input is smaller than address), including credit card inputs",
    "impact": 3.0,
    "cost": 1.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "checkout-optional-and-mandatory-fields-are-easily-distinguishable",
    "page": "checkout",
    "pageLabel": "Checkout page",
    "section": "Conversion and AOV 'boosters'",
    "checkpoint": "Optional and mandatory fields are easily distinguishable",
    "impact": 3.0,
    "cost": 1.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "checkout-if-we-are-asking-for-the-phone-number-we-must-explain-beside-below-the",
    "page": "checkout",
    "pageLabel": "Checkout page",
    "section": "Conversion and AOV 'boosters'",
    "checkpoint": "If we are asking for the phone number, we must explain beside/below the input that it's only for delivery information",
    "impact": 3.0,
    "cost": 1.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "checkout-checkout-is-using-a-database-of-street-addresses-so-the-user-cannot-mi",
    "page": "checkout",
    "pageLabel": "Checkout page",
    "section": "Conversion and AOV 'boosters'",
    "checkpoint": "Checkout is using a database of street addresses so the user cannot mistype the address",
    "impact": 2.0,
    "cost": 3.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "checkout-input-fields-use-inline-validation-with-a-prominent-green-red-border-a",
    "page": "checkout",
    "pageLabel": "Checkout page",
    "section": "Conversion and AOV 'boosters'",
    "checkpoint": "Input fields use inline validation with a prominent green/red border and arrow/x sign (e.g, if the email is correctly entered)",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "checkout-the-error-state-of-incorrectly-filled-out-input-fields-clearly-states-",
    "page": "checkout",
    "pageLabel": "Checkout page",
    "section": "Conversion and AOV 'boosters'",
    "checkpoint": "The error state of incorrectly filled out input fields clearly states what is wrong and how it should be corrected",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "checkout-the-user-does-not-need-to-enter-the-same-information-more-than-once",
    "page": "checkout",
    "pageLabel": "Checkout page",
    "section": "Conversion and AOV 'boosters'",
    "checkpoint": "The user does not need to enter the same information more than once",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "checkout-checkout-uses-an-auto-complete-function-wherever-possible-e-g-when-use",
    "page": "checkout",
    "pageLabel": "Checkout page",
    "section": "Conversion and AOV 'boosters'",
    "checkpoint": "Checkout uses an auto-complete function wherever possible (e.g. when user types in the postal code, the city gets filled out automatically)",
    "impact": 3.0,
    "cost": 3.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "checkout-if-the-user-leaves-the-checkout-and-then-returns-the-input-fields-will",
    "page": "checkout",
    "pageLabel": "Checkout page",
    "section": "Conversion and AOV 'boosters'",
    "checkpoint": "If the user leaves the checkout and then returns, the input fields will have been saved so they can continue where they left off",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "checkout-input-fields-have-an-option-x-icon-at-the-right-side-to-delete-the-con",
    "page": "checkout",
    "pageLabel": "Checkout page",
    "section": "Conversion and AOV 'boosters'",
    "checkpoint": "Input fields have an option (\"X\" icon at the right side) to delete the content with one click",
    "impact": 2.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "thankyou-thank-you-page-clearly-states-that-the-user-successfully-completed-the",
    "page": "thankyou",
    "pageLabel": "Thank you page",
    "section": "General",
    "checkpoint": "Thank you page clearly states that the user successfully completed the purchase and congratulates them",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "thankyou-thank-you-page-clearly-sumarizes-what-was-in-the-order",
    "page": "thankyou",
    "pageLabel": "Thank you page",
    "section": "General",
    "checkpoint": "Thank you page clearly sumarizes what was in the order",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "thankyou-thank-you-page-clearly-states-when-the-package-will-arrive-and-with-wh",
    "page": "thankyou",
    "pageLabel": "Thank you page",
    "section": "General",
    "checkpoint": "Thank you page clearly states when the package will arrive and with what courier / delivery service",
    "impact": 3.0,
    "cost": 3.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "thankyou-thank-you-page-offers-an-easy-way-for-the-user-to-get-in-touch-with-th",
    "page": "thankyou",
    "pageLabel": "Thank you page",
    "section": "General",
    "checkpoint": "Thank you page offers an easy way for the user to get in touch with the store owner(e.g. live chat, email, phone number)",
    "impact": 3.0,
    "cost": 1.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "thankyou-the-thank-you-page-explains-to-the-user-how-they-can-track-their-packa",
    "page": "thankyou",
    "pageLabel": "Thank you page",
    "section": "General",
    "checkpoint": "The thank you page explains to the user how they can track their package",
    "impact": 2.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  },
  {
    "id": "thankyou-thank-you-page-offers-the-user-to-buy-additional-items-quantity-of-the",
    "page": "thankyou",
    "pageLabel": "Thank you page",
    "section": "Conversion and AOV 'boosters'",
    "checkpoint": "Thank you page offers the user to buy additional items/quantity of the same product at a lower price, or buy another complementary product, with a clear explanation that these additional items will be combined with their recently made order)",
    "impact": 3.0,
    "cost": 3.0,
    "priorityScore": 5.4,
    "defaultEvaluation": "Bad",
    "tier": "basic"
  },
  {
    "id": "thankyou-thank-you-page-offers-the-user-a-coupon-code-that-they-can-use-for-the",
    "page": "thankyou",
    "pageLabel": "Thank you page",
    "section": "Conversion and AOV 'boosters'",
    "checkpoint": "Thank you page offers the user a coupon code that they can use for their next purchase, or give it to their friends",
    "impact": 3.0,
    "cost": 2.0,
    "priorityScore": 0,
    "defaultEvaluation": "Not Relevant",
    "tier": "basic"
  },
  {
    "id": "thankyou-the-user-receives-a-summary-of-all-information-in-their-confirmation-e",
    "page": "thankyou",
    "pageLabel": "Thank you page",
    "section": "Conversion and AOV 'boosters'",
    "checkpoint": "The user receives a summary of all information in their confirmation email (product summary, upsells, coupon code that is on the thank you page, etc.)",
    "impact": 3.0,
    "cost": 3.0,
    "priorityScore": 0,
    "defaultEvaluation": "Good",
    "tier": "basic"
  }
];
